# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FinishD = QtWidgets.QPushButton(self.centralwidget)
        self.FinishD.setGeometry(QtCore.QRect(310, 360, 171, 31))
        self.FinishD.setStyleSheet("border-radius: 14px;\n"
                                   "color: rgb(0,0,0);\n"
                                   "border: 2px solid#094069;\n"
                                   "background-color: rgb(255,255,255);\n"
                                   "")
        self.FinishD.setObjectName("FinishD")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 410, 101, 41))
        self.pushButton_2.setStyleSheet("border-radius: 20px;\n"
                                        "color: rgb(255,255,255);\n"
                                        "border: 2px solid#094069;\n"
                                        "background-color: rgb(80,150,230);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.BotAnswer = QtWidgets.QTextEdit(self.centralwidget)
        self.BotAnswer.setGeometry(QtCore.QRect(150, 6, 481, 391))
        self.BotAnswer.setObjectName("BotAnswer")
        self.UserText = QtWidgets.QTextEdit(self.centralwidget)
        self.UserText.setGeometry(QtCore.QRect(150, 410, 481, 41))
        self.UserText.setStyleSheet("border-radius:9px;\n"
                                    "border: 3px solid#b4b4b4\n"
                                    "")
        self.UserText.setObjectName("UserText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 410, 141, 41))
        self.label.setStyleSheet("\n"
                                 "color: rgb(155, 155, 155);")
        self.label.setObjectName("label")

        # Добавляем новую кнопку pushButton_3 слева от pushButton_2
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 410, 101, 41))
        self.pushButton_3.setStyleSheet("border-radius: 20px;\n"
                                        "color: rgb(255,255,255);\n"
                                        "border: 2px solid#094069;\n"
                                        "background-color: rgb(80,150,230);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setText("Голосовой ввод")

        self.pushButton_2.raise_()
        self.BotAnswer.raise_()
        self.UserText.raise_()
        self.FinishD.raise_()
        self.label.raise_()
        self.pushButton_3.raise_()  # Поднять новую кнопку на верхний слой
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menudfdf = QtWidgets.QMenu(self.menubar)
        self.menudfdf.setObjectName("menudfdf")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menudfdf.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FinishD.setText(_translate("MainWindow", "Очистить историю диалога"))
        self.pushButton_2.setText(_translate("MainWindow", "Отправить"))
        self.label.setText(_translate("MainWindow", "Введите сообщение"))
        self.menudfdf.setTitle(_translate("MainWindow", "dfdf"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())